version: '3.9'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/server/static
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - ./server:/app/server
      - static:/app/server/static
    restart: always
    ports:
      - 8100:8100
    env_file:
      - ./server/.env
  worker:
    container_name: celery
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    entrypoint: /app/server/scripts/worker-entrypoint.sh
    volumes:
      - static:/app/server/static
    env_file:
      - ./server/.env
    depends_on:
      - api
      - redis
  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  static:
