version: '3.9'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/server/static
  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
      - ./server:/app/server
      - static:/app/server/static
    restart: always
    ports:
      - 8100:8100
    env_file:
      - ./server/.env

volumes:
  static:
